GET  http://localhost:3001/todos

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
     "text": "take bath"
}

###
DELETE http://localhost:3001/todo/delete/6576dfceb8185b92c79865d3

###
PUT  http://localhost:3001/todo/complete/6576b8ecce4b30d13f4ff3fb